const demoGov=[
 {state:'Delhi',bus:'DTC 861A',from:'Jahangir Puri',to:'Tilak Nagar',time:'Approx. 75 min',fare:'₹10–₹25',stops:['Jahangir Puri','Uttam Nagar','Tilak Nagar'],note:'Journey time varies with traffic; fare shown as current indicative DTC city-bus range.'},
 {state:'Delhi',bus:'DTC 873',from:'Tilak Nagar',to:'Tajpur Khurd',time:'Approx. 65 min',fare:'₹10–₹25',stops:['Tilak Nagar','Najafgarh','Tajpur Khurd'],note:'Journey time is an indicative road-time estimate, not an official timetable duration.'},
 {state:'Delhi',bus:'DTC 876',from:'Tilak Nagar',to:'Dichaun Kalan',time:'Approx. 55 min',fare:'₹10–₹25',stops:['Tilak Nagar','Dichaun Kalan'],note:'Journey time varies by traffic and service conditions.'},
 {state:'Delhi',bus:'DTC 845',from:'Tilak Nagar',to:'Daulat Pur',time:'Approx. 60 min',fare:'₹10–₹25',stops:['Tilak Nagar','Daulat Pur'],note:'Indicative journey time; check operator information for exact fare.'},
 {state:'Delhi',bus:'DTC 848',from:'Tilak Nagar',to:'Bakkargarh Border',time:'Approx. 80 min',fare:'₹10–₹30',stops:['Tilak Nagar','Najafgarh','Bakkargarh Border'],note:'Indicative journey time; traffic can change the actual duration.'},
 {state:'Delhi',bus:'DTC 871',from:'Vikas Puri H-3',to:'Tilak Nagar',time:'Approx. 25 min',fare:'₹10–₹15',stops:['Vikas Puri H-3','Tilak Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 825A',from:'Tilak Nagar',to:'Tikari Border',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Tikari Border'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 826',from:'Tilak Nagar',to:'Khera Dabar Village Chowk',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Khera Dabar Village Chowk'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 827',from:'Tilak Nagar',to:'Daurala Border',time:'Approx. 85 min',fare:'₹10–₹30',stops:['Tilak Nagar','Daurala Border'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 829',from:'Tilak Nagar',to:'Shikar Pur',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Shikar Pur'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 810',from:'Kendriya Terminal',to:'Uttam Nagar',time:'Approx. 50 min',fare:'₹10–₹25',stops:['Kendriya Terminal','Uttam Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 818',from:'Tilak Nagar',to:'Jhatikara Village',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Jhatikara Village'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 819',from:'Tilak Nagar',to:'Pandwala Kalan',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Pandwala Kalan'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 824',from:'Tilak Nagar',to:'Kair Village',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Kair Village'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 828',from:'Ghumanhera',to:'Uttam Nagar',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Ghumanhera','Uttam Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 847',from:'Uttam Nagar',to:'New Seemapuri',time:'Approx. 85 min',fare:'₹10–₹30',stops:['Uttam Nagar','New Seemapuri'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 764',from:'Tilak Nagar',to:'Uttam Nagar',time:'Approx. 35 min',fare:'₹10–₹20',stops:['Tilak Nagar','Janakpuri East','Dabri Crossing','Uttam Nagar'],note:'Route example for local journey search.'},
 {state:'Delhi',bus:'DTC 728',from:'Dwarka',to:'Rajouri Garden',time:'Approx. 52 min',fare:'₹10–₹25',stops:['Dwarka Sector 10','Dhaula Kuan','Naraina','Rajouri Garden'],note:'Route example for local journey search.'},
 {state:'Haryana',bus:'GMCBL 212',from:'Gurugram',to:'Dwarka',time:'Approx. 65 min',fare:'₹20–₹40',stops:['Gurugram Bus Stand','IFFCO Chowk','MG Road','Dwarka Sector 21'],note:'Indicative journey time; verify operator fare.'}
];

let firestore,auth,currentOrg=null,busUnsubscribe=null,passengerUnsubscribe=null,gpsWatches={};
try{firebase.initializeApp(window.firebaseConfig);firestore=firebase.firestore();auth=firebase.auth()}catch(err){console.error('Firebase initialization failed',err);}

function code(){return 'RP-'+Math.random().toString(36).slice(2,5).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function msg(id,text,type){const el=document.getElementById(id);if(el)el.innerHTML=`<div class="${type}">${text}</div>`}
function firebaseError(err){const map={auth/operation-not-allowed:'Email/password sign-in is not enabled in Firebase. Open Firebase Console → Authentication → Sign-in method and enable Email/Password.',auth/email-already-in-use:'This email is already registered. Use the Admin Login instead.',auth/invalid-credential:'Invalid email or password.',auth/invalid-email:'Please enter a valid email address.',auth/weak-password:'Password must be at least 6 characters.'};return map[err.code]||err.message||'Something went wrong. Please try again.'}

function searchGov(){const f=document.getElementById('govFrom').value.trim().toLowerCase(),t=document.getElementById('govTo').value.trim().toLowerCase(),s=document.getElementById('govState').value;let r=demoGov.filter(x=>(s==='all'||x.state===s)&&(!f||x.from.toLowerCase().includes(f)||x.stops.some(z=>z.toLowerCase().includes(f)))&&(!t||x.to.toLowerCase().includes(t)||x.stops.some(z=>z.toLowerCase().includes(t))));document.getElementById('govResults').innerHTML=r.length?r.map(x=>`<article class="route-card"><div><div class="route-name">${x.bus} · ${x.from} → ${x.to}</div><div class="route-meta">${x.state} · Stops: ${x.stops.join(' → ')}</div><div class="route-meta">${x.note}</div></div><div><b>${x.time}</b><div class="route-meta">journey time</div></div><div><div class="fare">${x.fare}</div><div class="route-meta">fare</div></div></article>`).join(''):'<div class="empty">No matching route in the current dataset. Try <b>Tilak Nagar → Uttam Nagar</b>.</div>'}

async function registerOrg(e){e.preventDefault();if(!auth||!firestore)return msg('registrationResult','Firebase is not connected. Refresh the page and try again.','error');const type=document.getElementById('orgType').value,name=document.getElementById('orgName').value.trim(),email=document.getElementById('orgEmail').value.trim().toLowerCase(),password=document.getElementById('orgPassword').value;try{const cred=await auth.createUserWithEmailAndPassword(email,password);let orgCode=code(),exists=await firestore.collection('organisations').where('code','==',orgCode).limit(1).get();while(!exists.empty){orgCode=code();exists=await firestore.collection('organisations').where('code','==',orgCode).limit(1).get()}const org={uid:cred.user.uid,type,name,email,code:orgCode,createdAt:firebase.firestore.FieldValue.serverTimestamp()};await firestore.collection('organisations').doc(cred.user.uid).set(org);currentOrg={id:cred.user.uid,...org};msg('registrationResult',`<b>Registration successful.</b><br>Your unique passenger code is <strong>${orgCode}</strong>.<br>Passengers can enter this code on <strong>any device</strong>.`,'success');e.target.reset();renderDashboard(currentOrg)}catch(err){console.error(err);msg('registrationResult',firebaseError(err),'error')}}

async function adminLogin(e){e.preventDefault();if(!auth||!firestore)return msg('loginResult','Firebase is not connected. Refresh the page and try again.','error');const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;try{const cred=await auth.signInWithEmailAndPassword(email,password);const snap=await firestore.collection('organisations').doc(cred.user.uid).get();if(!snap.exists){await auth.signOut();return msg('loginResult','This account has no RoutePulse organisation profile.','error')}currentOrg={id:snap.id,...snap.data()};msg('loginResult',`Logged in as <b>${esc(currentOrg.name)}</b>.`,'success');renderDashboard(currentOrg)}catch(err){console.error(err);msg('loginResult',firebaseError(err),'error')}}

function renderDashboard(org){currentOrg=org;const box=document.getElementById('dashboard');box.classList.remove('hidden');if(busUnsubscribe)busUnsubscribe();box.innerHTML=`<div class="card"><span class="eyebrow">ADMIN DASHBOARD</span><h3>${esc(org.name)}</h3><p class="route-meta">Organisation code: <b>${esc(org.code)}</b> — share this code with passengers.</p><div class="dashboard-grid"><div class="stat"><span class="route-meta">Buses</span><b id="busCount">0</b></div><div class="stat"><span class="route-meta">Tracking</span><b id="trackingState">Ready</b></div><div class="stat"><span class="route-meta">Passenger code</span><b>${esc(org.code)}</b></div></div><form class="bus-form" onsubmit="addBus(event)"><label>Bus number<input name="bus" required placeholder="e.g. RP-101"></label><label>Driver name<input name="driver" required placeholder="Driver name"></label><label>Driver phone<input name="phone" required placeholder="10 digit number"></label><label>Route name<input name="route" required placeholder="Tilak Nagar to Uttam Nagar"></label><label>Start point<input name="start" required></label><label>End point<input name="end" required></label><label class="full">Stops (comma separated)<input name="stops" required placeholder="Stop 1, Stop 2, Stop 3"></label><label>Schedule note<input name="schedule" placeholder="Arrival/departure details"></label><button class="btn primary">Add bus</button></form><div id="busList"><div class="empty">Loading buses…</div></div></div>`;busUnsubscribe=firestore.collection('organisations').doc(org.id).collection('buses').orderBy('createdAt','desc').onSnapshot(snap=>{const buses=snap.docs.map(d=>({id:d.id,...d.data()}));document.getElementById('busCount').textContent=buses.length;document.getElementById('trackingState').textContent=buses.some(b=>b.live)?'LIVE':'Ready';document.getElementById('busList').innerHTML=busList(org,buses)},err=>{console.error(err);document.getElementById('busList').innerHTML='<div class="empty">Unable to load buses. Check Firestore rules.</div>'})}

function busList(o,buses){return buses.length?`<h3 style="margin-top:30px">Your buses</h3>`+buses.map(b=>`<div class="route-card"><div><div class="route-name">${esc(b.bus)} · ${esc(b.route)}</div><div class="route-meta">Driver: ${esc(b.driver)} · ${esc(b.phone)}<br>${esc(b.start)} → ${esc(b.end)}<br>Stops: ${esc((b.stops||[]).join(' → '))}</div></div><div><b>${esc(b.schedule||'Timetable added')}</b><div class="route-meta">${b.live?'GPS active':'GPS ready'}${b.updatedAt?' · '+new Date(b.updatedAt.seconds*1000).toLocaleTimeString():''}</div></div><div class="route-actions"><button class="btn ghost" onclick="editBus('${o.id}','${b.id}')">Edit details</button><button class="btn ${b.live?'ghost':'primary'}" onclick="toggleGPS('${o.id}','${b.id}')">${b.live?'Stop GPS':'Enable GPS'}</button></div></div>`).join(''):'<div class="empty" style="margin-top:20px">No buses added yet.</div>'}

async function addBus(e){e.preventDefault();if(!currentOrg)return;const f=new FormData(e.target);try{await firestore.collection('organisations').doc(currentOrg.id).collection('buses').add({bus:f.get('bus'),driver:f.get('driver'),phone:f.get('phone'),route:f.get('route'),start:f.get('start'),end:f.get('end'),stops:f.get('stops').split(',').map(x=>x.trim()).filter(Boolean),schedule:f.get('schedule'),live:false,lat:null,lng:null,createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset()}catch(err){alert(firebaseError(err))}}

async function editBus(orgId,busId){const ref=firestore.collection('organisations').doc(orgId).collection('buses').doc(busId),snap=await ref.get();if(!snap.exists)return;const b=snap.data(),box=document.getElementById('dashboard');box.querySelector('.bus-form').outerHTML=`<form class="bus-form" onsubmit="updateBus(event,'${orgId}','${busId}')"><h3 class="full">Edit bus details</h3><label>Bus number<input name="bus" required value="${esc(b.bus)}"></label><label>Driver name<input name="driver" required value="${esc(b.driver)}"></label><label>Driver phone<input name="phone" required value="${esc(b.phone)}"></label><label>Route name<input name="route" required value="${esc(b.route)}"></label><label>Start point<input name="start" required value="${esc(b.start)}"></label><label>End point<input name="end" required value="${esc(b.end)}"></label><label class="full">Stops (comma separated)<input name="stops" required value="${esc((b.stops||[]).join(', '))}"></label><label>Schedule note<input name="schedule" value="${esc(b.schedule||'')}"></label><div class="full"><button class="btn primary">Save changes</button> <button type="button" class="btn ghost" onclick="renderDashboard(currentOrg)">Cancel</button></div></form>`}

async function updateBus(e,orgId,busId){e.preventDefault();const f=new FormData(e.target);try{await firestore.collection('organisations').doc(orgId).collection('buses').doc(busId).update({bus:f.get('bus'),driver:f.get('driver'),phone:f.get('phone'),route:f.get('route'),start:f.get('start'),end:f.get('end'),stops:f.get('stops').split(',').map(x=>x.trim()).filter(Boolean),schedule:f.get('schedule')});renderDashboard(currentOrg)}catch(err){alert(firebaseError(err))}}

function toggleGPS(orgId,busId){const ref=firestore.collection('organisations').doc(orgId).collection('buses').doc(busId);if(gpsWatches[busId]){navigator.geolocation.clearWatch(gpsWatches[busId]);delete gpsWatches[busId];ref.update({live:false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(console.error);return}if(!navigator.geolocation)return alert('This browser does not support GPS.');const watchId=navigator.geolocation.watchPosition(pos=>{ref.update({live:true,lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(console.error)},err=>{alert('Location permission was not granted: '+err.message);delete gpsWatches[busId];ref.update({live:false}).catch(()=>{})},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});gpsWatches[busId]=watchId;ref.update({live:true}).catch(console.error)}

async function passengerLookup(){const c=document.getElementById('orgCodeInput').value.trim().toUpperCase(),box=document.getElementById('passengerResults');if(passengerUnsubscribe){passengerUnsubscribe();passengerUnsubscribe=null}if(!c)return box.innerHTML='<div class="empty">Enter an organisation code.</div>';try{const snap=await firestore.collection('organisations').where('code','==',c).limit(1).get();if(snap.empty)return box.innerHTML='<div class="empty">Organisation code not found. Ask the operator for the correct code.</div>';const orgDoc=snap.docs[0],org={id:orgDoc.id,...orgDoc.data()};box.innerHTML=`<div class="results"><div class="card"><span class="eyebrow">ORGANISATION</span><h3>${esc(org.name)}</h3><p class="route-meta">${esc(org.type)} · Code ${esc(org.code)}</p><div id="passengerBusList"><div class="empty">Loading buses…</div></div></div></div>`;passengerUnsubscribe=firestore.collection('organisations').doc(org.id).collection('buses').orderBy('createdAt','desc').onSnapshot(busSnap=>{const buses=busSnap.docs.map(d=>({id:d.id,...d.data()}));document.getElementById('passengerBusList').innerHTML=buses.length?buses.map(b=>`<article class="route-card"><div><div class="route-name">${esc(b.bus)} · ${esc(b.route)}</div><div class="route-meta">${esc(b.start)} → ${esc(b.end)}<br>Stops: ${esc((b.stops||[]).join(' → '))}<br>${esc(b.schedule||'Schedule provided by operator')}</div></div><div>${b.live&&typeof b.lat==='number'&&typeof b.lng==='number'?`<b style="color:var(--green)">● LIVE</b><div class="route-meta">${b.updatedAt?'Updated '+new Date(b.updatedAt.seconds*1000).toLocaleTimeString():'Updating now'}<br>GPS: ${b.lat.toFixed(5)}, ${b.lng.toFixed(5)}</div>`:'<b>Not live</b><div class="route-meta">Driver has not enabled GPS</div>'}</div><div>${b.live&&typeof b.lat==='number'&&typeof b.lng==='number'?`<a class="btn primary" target="_blank" href="https://www.google.com/maps?q=${b.lat},${b.lng}">Map</a>`:''}</div></article>`).join(''):'<div class="empty">This organisation has not added any buses yet.</div>'},err=>{console.error(err);document.getElementById('passengerBusList').innerHTML='<div class="empty">Unable to load buses. Check Firestore rules.</div>'})}catch(err){console.error(err);box.innerHTML=`<div class="empty">${esc(firebaseError(err))}</div>`}}

searchGov();
