const KEY='routepulse-v1';
const demoGov=[
 {state:'Delhi',bus:'DTC 764',from:'Tilak Nagar',to:'Uttam Nagar',time:'35 min',fare:'₹15',stops:['Tilak Nagar','Janakpuri East','Dabri Crossing','Uttam Nagar']},
 {state:'Delhi',bus:'DTC 728',from:'Dwarka',to:'Rajouri Garden',time:'52 min',fare:'₹20',stops:['Dwarka Sector 10','Dhaula Kuan','Naraina','Rajouri Garden']},
 {state:'Haryana',bus:'GMCBL 212',from:'Gurugram',to:'Dwarka',time:'65 min',fare:'₹30',stops:['Gurugram Bus Stand','IFFCO Chowk','MG Road','Dwarka Sector 21']}
];
function db(){try{return JSON.parse(localStorage.getItem(KEY))||{orgs:[]}}catch{return {orgs:[]}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function code(){return 'RP-'+Math.random().toString(36).slice(2,5).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function searchGov(){const f=document.getElementById('govFrom').value.trim().toLowerCase(),t=document.getElementById('govTo').value.trim().toLowerCase(),s=document.getElementById('govState').value;let r=demoGov.filter(x=>(s==='all'||x.state===s)&&(!f||x.from.toLowerCase().includes(f)||x.stops.some(z=>z.toLowerCase().includes(f)))&&(!t||x.to.toLowerCase().includes(t)||x.stops.some(z=>z.toLowerCase().includes(t))));document.getElementById('govResults').innerHTML=r.length?r.map(x=>`<article class="route-card"><div><div class="route-name">${x.bus} · ${x.from} → ${x.to}</div><div class="route-meta">${x.state} · Stops: ${x.stops.join(' → ')}</div></div><div><b>${x.time}</b><div class="route-meta">journey time · timetable demo</div></div><div><div class="fare">${x.fare}</div><div class="route-meta">fare</div></div></article>`).join(''):'<div class="empty">No matching route in the current verified/demo dataset. Try <b>Tilak Nagar → Uttam Nagar</b>.</div>'}
function registerOrg(e){e.preventDefault();const d=db(),email=document.getElementById('orgEmail').value.trim().toLowerCase();if(d.orgs.some(o=>o.email===email)){return msg('registrationResult','An organisation already uses this email.','error')}const org={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),type:orgType.value,name:orgName.value.trim(),email,password:orgPassword.value,code:code(),buses:[]};d.orgs.push(org);save(d);msg('registrationResult',`<b>Registration successful.</b><br>Your unique organisation code is <strong>${org.code}</strong>. Save this code and share it with passengers.`,'success');e.target.reset()}
function adminLogin(e){e.preventDefault();const d=db(),o=d.orgs.find(x=>x.email===loginEmail.value.trim().toLowerCase()&&x.password===loginPassword.value);if(!o)return msg('loginResult','Invalid email or password.','error');msg('loginResult',`Logged in as <b>${o.name}</b>.`,'success');renderDashboard(o)}
function renderDashboard(org){const box=document.getElementById('dashboard');box.classList.remove('hidden');box.innerHTML=`<div class="card"><span class="eyebrow">ADMIN DASHBOARD</span><h3>${org.name}</h3><p class="route-meta">Organisation code: <b>${org.code}</b></p><div class="dashboard-grid"><div class="stat"><span class="route-meta">Buses</span><b>${org.buses.length}</b></div><div class="stat"><span class="route-meta">Tracking</span><b>${org.buses.some(b=>b.live)?'LIVE':'Ready'}</b></div><div class="stat"><span class="route-meta">Passenger code</span><b>${org.code}</b></div></div><form class="bus-form" onsubmit="addBus(event,'${org.id}')"><label>Bus number<input name="bus" required placeholder="e.g. RP-101"></label><label>Driver name<input name="driver" required placeholder="Driver name"></label><label>Driver phone<input name="phone" required placeholder="10 digit number"></label><label>Route name<input name="route" required placeholder="Tilak Nagar to Uttam Nagar"></label><label>Start point<input name="start" required></label><label>End point<input name="end" required></label><label class="full">Stops (comma separated)<input name="stops" required placeholder="Stop 1, Stop 2, Stop 3"></label><label>Schedule note<input name="schedule" placeholder="Arrival/departure details"></label><button class="btn primary">Add bus</button></form><div id="busList">${busList(org)}</div></div>`}
function busList(o){return o.buses.length?`<h3 style="margin-top:30px">Your buses</h3>`+o.buses.map((b,i)=>`<div class="route-card"><div><div class="route-name">${b.bus} · ${b.route}</div><div class="route-meta">Driver: ${b.driver} · ${b.phone}<br>${b.start} → ${b.end}<br>Stops: ${b.stops.join(' → ')}</div></div><div><b>${b.schedule||'Timetable added'}</b><div class="route-meta">${b.live?'GPS active':'GPS ready'}</div></div><button class="btn ${b.live?'ghost':'primary'}" onclick="toggleGPS('${o.id}',${i})">${b.live?'Stop GPS':'Enable GPS'}</button></div>`).join(''):'<div class="empty" style="margin-top:20px">No buses added yet.</div>'}
function addBus(e,id){e.preventDefault();const f=new FormData(e.target),d=db(),o=d.orgs.find(x=>x.id===id);o.buses.push({bus:f.get('bus'),driver:f.get('driver'),phone:f.get('phone'),route:f.get('route'),start:f.get('start'),end:f.get('end'),stops:f.get('stops').split(',').map(x=>x.trim()).filter(Boolean),schedule:f.get('schedule'),live:false,lat:null,lng:null});save(d);renderDashboard(o)}
function toggleGPS(id,i){const d=db(),o=d.orgs.find(x=>x.id===id),b=o.buses[i];if(b.live){b.live=false;save(d);renderDashboard(o);return}if(!navigator.geolocation)return alert('This browser does not support GPS.');navigator.geolocation.getCurrentPosition(pos=>{b.live=true;b.lat=pos.coords.latitude;b.lng=pos.coords.longitude;b.updated=new Date().toLocaleTimeString();save(d);renderDashboard(o)},()=>alert('Location permission was not granted.'))}
function passengerLookup(){const c=document.getElementById('orgCodeInput').value.trim().toUpperCase(),d=db(),o=d.orgs.find(x=>x.code===c),box=document.getElementById('passengerResults');if(!o){box.innerHTML='<div class="empty">Organisation code not found. Ask the operator for the correct code.</div>';return}box.innerHTML=`<div class="results"><div class="card"><span class="eyebrow">ORGANISATION</span><h3>${o.name}</h3><p class="route-meta">${o.type} · Code ${o.code}</p>${o.buses.length?o.buses.map(b=>`<article class="route-card"><div><div class="route-name">${b.bus} · ${b.route}</div><div class="route-meta">${b.start} → ${b.end}<br>Stops: ${b.stops.join(' → ')}<br>${b.schedule||'Schedule provided by operator'}</div></div><div>${b.live?`<b style="color:var(--green)">● LIVE</b><div class="route-meta">Updated ${b.updated||'now'}<br>${b.lat.toFixed(5)}, ${b.lng.toFixed(5)}</div>`:'<b>Not live</b><div class="route-meta">Driver has not enabled GPS</div>'}</div><div><a class="btn primary" target="_blank" href="https://www.google.com/maps?q=${b.lat||0},${b.lng||0}">Map</a></div></article>`).join(''):'<div class="empty">This organisation has not added any buses yet.</div>'}</div></div>`}
function msg(id,text,type){document.getElementById(id).innerHTML=`<div class="${type}">${text}</div>`}
searchGov();