const KEY='routepulse-v1';
const demoGov=[
 {state:'Delhi',bus:'DTC 861A',from:'Jahangir Puri',to:'Tilak Nagar',time:'Approx. 75 min',fare:'₹10–₹25',stops:['Jahangir Puri','Uttam Nagar','Tilak Nagar'],note:'Journey time varies with traffic; fare shown as current indicative DTC city-bus range.'},
 {state:'Delhi',bus:'DTC 873',from:'Tilak Nagar',to:'Tajpur Khurd',time:'Approx. 65 min',fare:'₹10–₹25',stops:['Tilak Nagar','Najafgarh','Tajpur Khurd'],note:'Journey time is an indicative road-time estimate, not an official timetable duration.'},
 {state:'Delhi',bus:'DTC 876',from:'Tilak Nagar',to:'Dichaun Kalan',time:'Approx. 55 min',fare:'₹10–₹25',stops:['Tilak Nagar','Dichaun Kalan'],note:'Journey time varies by traffic and service conditions.'},
 {state:'Delhi',bus:'DTC 845',from:'Tilak Nagar',to:'Daulat Pur',time:'Approx. 60 min',fare:'₹10–₹25',stops:['Tilak Nagar','Daulat Pur'],note:'Indicative journey time; check operator information for exact fare.'},
 {state:'Delhi',bus:'DTC 848',from:'Tilak Nagar',to:'Bakkargarh Border',time:'Approx. 80 min',fare:'₹10–₹30',stops:['Tilak Nagar','Najafgarh','Bakkargarh Border'],note:'Indicative journey time; traffic can change the actual duration.'},
 {state:'Delhi',bus:'DTC 871',from:'Vikas Puri H-3',to:'Tilak Nagar',time:'Approx. 25 min',fare:'₹10–₹15',stops:['Vikas Puri H-3','Tilak Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 825A',from:'Tilak Nagar',to:'Tikari Border',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Tikari Border'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 826',from:'Tilak Nagar',to:'Khera Dabar Village Chowk',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Khera Dabar Village Chowk'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 827',from:'Tilak Nagar',to:'Daurala Border',time:'Approx. 85 min',fare:'₹10–₹30',stops:['Tilak Nagar','Daurala Border'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 829',from:'Tilak Nagar',to:'Shikar Pur',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Shikar Pur'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 810',from:'Kendriya Terminal',to:'Uttam Nagar',time:'Approx. 50 min',fare:'₹10–₹25',stops:['Kendriya Terminal','Uttam Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 818',from:'Tilak Nagar',to:'Jhatikara Village',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Tilak Nagar','Jhatikara Village'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 819',from:'Tilak Nagar',to:'Pandwala Kalan',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Pandwala Kalan'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 824',from:'Tilak Nagar',to:'Kair Village',time:'Approx. 75 min',fare:'₹10–₹30',stops:['Tilak Nagar','Kair Village'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 828',from:'Ghumanhera',to:'Uttam Nagar',time:'Approx. 70 min',fare:'₹10–₹30',stops:['Ghumanhera','Uttam Nagar'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 847',from:'Uttam Nagar',to:'New Seemapuri',time:'Approx. 85 min',fare:'₹10–₹30',stops:['Uttam Nagar','New Seemapuri'],note:'Indicative journey time.'},
 {state:'Delhi',bus:'DTC 764',from:'Tilak Nagar',to:'Uttam Nagar',time:'Approx. 35 min',fare:'₹10–₹20',stops:['Tilak Nagar','Janakpuri East','Dabri Crossing','Uttam Nagar'],note:'Route example for local journey search.'},
 {state:'Delhi',bus:'DTC 728',from:'Dwarka',to:'Rajouri Garden',time:'Approx. 52 min',fare:'₹10–₹25',stops:['Dwarka Sector 10','Dhaula Kuan','Naraina','Rajouri Garden'],note:'Route example for local journey search.'},
 {state:'Haryana',bus:'GMCBL 212',from:'Gurugram',to:'Dwarka',time:'Approx. 65 min',fare:'₹20–₹40',stops:['Gurugram Bus Stand','IFFCO Chowk','MG Road','Dwarka Sector 21'],note:'Indicative journey time; verify operator fare.'}
];
function db(){try{return JSON.parse(localStorage.getItem(KEY))||{orgs:[]}}catch{return {orgs:[]}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function code(){return 'RP-'+Math.random().toString(36).slice(2,5).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function searchGov(){const f=document.getElementById('govFrom').value.trim().toLowerCase(),t=document.getElementById('govTo').value.trim().toLowerCase(),s=document.getElementById('govState').value;let r=demoGov.filter(x=>(s==='all'||x.state===s)&&(!f||x.from.toLowerCase().includes(f)||x.stops.some(z=>z.toLowerCase().includes(f)))&&(!t||x.to.toLowerCase().includes(t)||x.stops.some(z=>z.toLowerCase().includes(t))));document.getElementById('govResults').innerHTML=r.length?r.map(x=>`<article class="route-card"><div><div class="route-name">${x.bus} · ${x.from} → ${x.to}</div><div class="route-meta">${x.state} · Stops: ${x.stops.join(' → ')}</div><div class="route-meta">${x.note}</div></div><div><b>${x.time}</b><div class="route-meta">journey time</div></div><div><div class="fare">${x.fare}</div><div class="route-meta">fare</div></div></article>`).join(''):'<div class="empty">No matching route in the current dataset. Try <b>Tilak Nagar → Uttam Nagar</b>.</div>'}
function registerOrg(e){e.preventDefault();const d=db(),email=document.getElementById('orgEmail').value.trim().toLowerCase();if(d.orgs.some(o=>o.email===email)){return msg('registrationResult','An organisation already uses this email.','error')}const org={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),type:orgType.value,name:orgName.value.trim(),email,password:orgPassword.value,code:code(),buses:[]};d.orgs.push(org);save(d);msg('registrationResult',`<b>Registration successful.</b><br>Your unique organisation code is <strong>${org.code}</strong>. Save this code and share it with passengers.`,'success');e.target.reset()}
function adminLogin(e){e.preventDefault();const d=db(),o=d.orgs.find(x=>x.email===loginEmail.value.trim().toLowerCase()&&x.password===loginPassword.value);if(!o)return msg('loginResult','Invalid email or password.','error');msg('loginResult',`Logged in as <b>${o.name}</b>.`,'success');renderDashboard(o)}
function renderDashboard(org){const box=document.getElementById('dashboard');box.classList.remove('hidden');box.innerHTML=`<div class="card"><span class="eyebrow">ADMIN DASHBOARD</span><h3>${org.name}</h3><p class="route-meta">Organisation code: <b>${org.code}</b></p><div class="dashboard-grid"><div class="stat"><span class="route-meta">Buses</span><b>${org.buses.length}</b></div><div class="stat"><span class="route-meta">Tracking</span><b>${org.buses.some(b=>b.live)?'LIVE':'Ready'}</b></div><div class="stat"><span class="route-meta">Passenger code</span><b>${org.code}</b></div></div><form class="bus-form" onsubmit="addBus(event,'${org.id}')"><label>Bus number<input name="bus" required placeholder="e.g. RP-101"></label><label>Driver name<input name="driver" required placeholder="Driver name"></label><label>Driver phone<input name="phone" required placeholder="10 digit number"></label><label>Route name<input name="route" required placeholder="Tilak Nagar to Uttam Nagar"></label><label>Start point<input name="start" required></label><label>End point<input name="end" required></label><label class="full">Stops (comma separated)<input name="stops" required placeholder="Stop 1, Stop 2, Stop 3"></label><label>Schedule note<input name="schedule" placeholder="Arrival/departure details"></label><button class="btn primary">Add bus</button></form><div id="busList">${busList(org)}</div></div>`}
function busList(o){return o.buses.length?`<h3 style="margin-top:30px">Your buses</h3>`+o.buses.map((b,i)=>`<div class="route-card"><div><div class="route-name">${b.bus} · ${b.route}</div><div class="route-meta">Driver: ${b.driver} · ${b.phone}<br>${b.start} → ${b.end}<br>Stops: ${b.stops.join(' → ')}</div></div><div><b>${b.schedule||'Timetable added'}</b><div class="route-meta">${b.live?'GPS active':'GPS ready'}</div></div><div class="route-actions"><button class="btn ghost" onclick="editBus('${o.id}',${i})">Edit details</button><button class="btn ${b.live?'ghost':'primary'}" onclick="toggleGPS('${o.id}',${i})">${b.live?'Stop GPS':'Enable GPS'}</button></div></div>`).join(''):'<div class="empty" style="margin-top:20px">No buses added yet.</div>'}
function addBus(e,id){e.preventDefault();const f=new FormData(e.target),d=db(),o=d.orgs.find(x=>x.id===id);o.buses.push({bus:f.get('bus'),driver:f.get('driver'),phone:f.get('phone'),route:f.get('route'),start:f.get('start'),end:f.get('end'),stops:f.get('stops').split(',').map(x=>x.trim()).filter(Boolean),schedule:f.get('schedule'),live:false,lat:null,lng:null});save(d);renderDashboard(o)}
function editBus(id,i){const d=db(),o=d.orgs.find(x=>x.id===id),b=o.buses[i],box=document.getElementById('dashboard');box.querySelector('.bus-form').outerHTML=`<form class="bus-form" onsubmit="updateBus(event,'${id}',${i})"><h3 class="full">Edit bus details</h3><label>Bus number<input name="bus" required value="${esc(b.bus)}"></label><label>Driver name<input name="driver" required value="${esc(b.driver)}"></label><label>Driver phone<input name="phone" required value="${esc(b.phone)}"></label><label>Route name<input name="route" required value="${esc(b.route)}"></label><label>Start point<input name="start" required value="${esc(b.start)}"></label><label>End point<input name="end" required value="${esc(b.end)}"></label><label class="full">Stops (comma separated)<input name="stops" required value="${esc(b.stops.join(', '))}"></label><label>Schedule note<input name="schedule" value="${esc(b.schedule||'')}"></label><div class="full"><button class="btn primary">Save changes</button> <button type="button" class="btn ghost" onclick="renderDashboard(db().orgs.find(x=>x.id==='${id}'))">Cancel</button></div></form>`}
function updateBus(e,id,i){e.preventDefault();const f=new FormData(e.target),d=db(),o=d.orgs.find(x=>x.id===id),b=o.buses[i];b.bus=f.get('bus');b.driver=f.get('driver');b.phone=f.get('phone');b.route=f.get('route');b.start=f.get('start');b.end=f.get('end');b.stops=f.get('stops').split(',').map(x=>x.trim()).filter(Boolean);b.schedule=f.get('schedule');save(d);renderDashboard(o)}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function toggleGPS(id,i){const d=db(),o=d.orgs.find(x=>x.id===id),b=o.buses[i];if(b.live){b.live=false;save(d);renderDashboard(o);return}if(!navigator.geolocation)return alert('This browser does not support GPS.');navigator.geolocation.getCurrentPosition(pos=>{b.live=true;b.lat=pos.coords.latitude;b.lng=pos.coords.longitude;b.updated=new Date().toLocaleTimeString();save(d);renderDashboard(o)},()=>alert('Location permission was not granted.'))}
function passengerLookup(){const c=document.getElementById('orgCodeInput').value.trim().toUpperCase(),d=db(),o=d.orgs.find(x=>x.code===c),box=document.getElementById('passengerResults');if(!o){box.innerHTML='<div class="empty">Organisation code not found. Ask the operator for the correct code.</div>';return}box.innerHTML=`<div class="results"><div class="card"><span class="eyebrow">ORGANISATION</span><h3>${o.name}</h3><p class="route-meta">${o.type} · Code ${o.code}</p>${o.buses.length?o.buses.map(b=>`<article class="route-card"><div><div class="route-name">${b.bus} · ${b.route}</div><div class="route-meta">${b.start} → ${b.end}<br>Stops: ${b.stops.join(' → ')}<br>${b.schedule||'Schedule provided by operator'}</div></div><div>${b.live?`<b style="color:var(--green)">● LIVE</b><div class="route-meta">Updated ${b.updated||'now'}<br>${b.lat.toFixed(5)}, ${b.lng.toFixed(5)}</div>`:'<b>Not live</b><div class="route-meta">Driver has not enabled GPS</div>'}</div><div><a class="btn primary" target="_blank" href="https://www.google.com/maps?q=${b.lat||0},${b.lng||0}">Map</a></div></article>`).join(''):'<div class="empty">This organisation has not added any buses yet.</div>'}</div></div>`}
function msg(id,text,type){document.getElementById(id).innerHTML=`<div class="${type}">${text}</div>`}
searchGov();