// Route Tracker Firebase configuration
window.firebaseConfig = {
  apiKey: "AIzaSyCmFjqnJmFHJICeuiuEwZpbnd8kGV9tAqc",
  authDomain: "routepulse-india.firebaseapp.com",
  projectId: "routepulse-india",
  storageBucket: "routepulse-india.firebasestorage.app",
  messagingSenderId: "474571170677",
  appId: "1:474571170677:web:d152c6eb30727b1782293c",
  measurementId: "G-TBZ22V7ZGL"
};

// Dashboard loader is defined here because this file is loaded before the login handler.
(function(){
  function safe(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
  function fb(){const a=(firebase.apps&&firebase.apps.length)?firebase.app():firebase.initializeApp(window.firebaseConfig);return{auth:a.auth(),db:a.firestore()}}
  window.renderDashboard=async function(o){
    window.currentOrg=o;const d=document.getElementById('dashboard');if(!d)return;d.classList.remove('hidden');
    d.innerHTML='<div class="card"><span class="eyebrow">ADMIN DASHBOARD</span><h2>'+safe(o.name||'Organisation')+'</h2><p class="route-meta">Passenger code: <b>'+safe(o.code||'Not available')+'</b></p><div class="dashboard-grid"><div class="stat"><span class="route-meta">Buses</span><b id="rtCount">0</b></div><div class="stat"><span class="route-meta">Tracking</span><b id="rtState">Ready</b></div><div class="stat"><span class="route-meta">Code</span><b>'+safe(o.code||'')+'</b></div></div><h3>Add a bus</h3><form id="rtForm" class="bus-form"><label>Bus number<input name="bus" required placeholder="e.g. RP-101"></label><label>Driver name<input name="driver" required></label><label>Driver phone<input name="phone" required></label><label>Route name<input name="route" required placeholder="Tilak Nagar to Uttam Nagar"></label><label>Start point<input name="start" required></label><label>End point<input name="end" required></label><label class="full">Stops (comma separated)<input name="stops" required placeholder="Stop 1, Stop 2, Stop 3"></label><label>Schedule note<input name="schedule" placeholder="Arrival/departure details"></label><button class="btn primary" type="submit">Add bus</button></form><div id="rtList"><div class="empty">Loading buses…</div></div></div>';
    const form=document.getElementById('rtForm');form.onsubmit=window.addBus;
    try{const x=fb();if(window.rtUnsub)window.rtUnsub();window.rtUnsub=x.db.collection('organisations').doc(o.id).collection('buses').orderBy('createdAt','desc').onSnapshot(function(s){const bs=s.docs.map(q=>({id:q.id,...q.data()})),list=document.getElementById('rtList');document.getElementById('rtCount').textContent=bs.length;document.getElementById('rtState').textContent=bs.some(b=>b.live)?'LIVE':'Ready';list.innerHTML=bs.length?'<h3 style="margin-top:30px">Your buses</h3>'+bs.map(b=>'<div class="route-card"><div><div class="route-name">'+safe(b.bus)+' · '+safe(b.route)+'</div><div class="route-meta">Driver: '+safe(b.driver)+' · '+safe(b.phone)+'<br>'+safe(b.start)+' → '+safe(b.end)+'<br>Stops: '+safe((b.stops||[]).join(' → '))+'</div></div><div><b>'+safe(b.schedule||'Timetable added')+'</b><div class="route-meta">'+(b.live?'GPS active':'GPS ready')+'</div></div><div class="route-actions"><button class="btn ghost" type="button" onclick="editBus(\''+safe(o.id)+'\',\''+safe(b.id)+'\')">Edit details</button><button class="btn '+(b.live?'ghost':'primary')+'" type="button" onclick="toggleGPS(\''+safe(o.id)+'\',\''+safe(b.id)+'\')">'+(b.live?'Stop GPS':'Enable GPS')+'</button></div></div>').join(''):'<div class="empty" style="margin-top:20px">No buses added yet.</div>'},function(e){document.getElementById('rtList').innerHTML='<div class="empty">Unable to load buses.<br><small>'+safe(e.message||e)+'</small></div>'})}catch(e){document.getElementById('rtList').innerHTML='<div class="empty">Firebase connection failed.<br><small>'+safe(e.message||e)+'</small></div>'}
  };
  window.addBus=async function(e){e.preventDefault();try{const x=fb(),f=new FormData(e.target);await x.db.collection('organisations').doc(window.currentOrg.id).collection('buses').add({bus:String(f.get('bus')).trim(),driver:String(f.get('driver')).trim(),phone:String(f.get('phone')).trim(),route:String(f.get('route')).trim(),start:String(f.get('start')).trim(),end:String(f.get('end')).trim(),stops:String(f.get('stops')).split(',').map(v=>v.trim()).filter(Boolean),schedule:String(f.get('schedule')||'').trim(),live:false,lat:null,lng:null,createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset()}catch(e){alert(e.message||e)}};
  window.editBus=async function(orgId,busId){try{const x=fb(),r=x.db.collection('organisations').doc(orgId).collection('buses').doc(busId),s=await r.get(),b=s.data(),f=document.getElementById('rtForm');f.outerHTML='<form id="rtForm" class="bus-form"><h3 class="full">Edit bus details</h3><label>Bus number<input name="bus" required value="'+safe(b.bus)+'"></label><label>Driver name<input name="driver" required value="'+safe(b.driver)+'"></label><label>Driver phone<input name="phone" required value="'+safe(b.phone)+'"></label><label>Route name<input name="route" required value="'+safe(b.route)+'"></label><label>Start point<input name="start" required value="'+safe(b.start)+'"></label><label>End point<input name="end" required value="'+safe(b.end)+'"></label><label class="full">Stops (comma separated)<input name="stops" required value="'+safe((b.stops||[]).join(', '))+'"></label><label>Schedule note<input name="schedule" value="'+safe(b.schedule||'')+'"></label><button class="btn primary" type="submit">Save changes</button> <button class="btn ghost" type="button" onclick="renderDashboard(currentOrg)">Cancel</button></form>';document.getElementById('rtForm').onsubmit=function(e){e.preventDefault();const z=new FormData(e.target);r.update({bus:z.get('bus'),driver:z.get('driver'),phone:z.get('phone'),route:z.get('route'),start:z.get('start'),end:z.get('end'),stops:z.get('stops').split(',').map(v=>v.trim()).filter(Boolean),schedule:z.get('schedule')}).then(()=>renderDashboard(currentOrg)).catch(e=>alert(e.message||e))} }catch(e){alert(e.message||e)}};
  window.toggleGPS=function(orgId,busId){try{const x=fb(),r=x.db.collection('organisations').doc(orgId).collection('buses').doc(busId);window.rtGps=window.rtGps||{};if(window.rtGps[busId]){navigator.geolocation.clearWatch(window.rtGps[busId]);delete window.rtGps[busId];r.update({live:false});return}if(!navigator.geolocation)return alert('GPS is not supported by this browser.');window.rtGps[busId]=navigator.geolocation.watchPosition(p=>r.update({live:true,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}),e=>{delete window.rtGps[busId];r.update({live:false});alert('GPS permission error: '+e.message)},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});r.update({live:true})}catch(e){alert(e.message||e)}};
})();